export enum QueryKey {
  PRINCIPALS = "principals",
  PRINCIPAL_ME = "principalMe",
  BENEFICIARIES = "beneficiaries",
  BENEFICIARY = "beneficiary",
  DEPENDENTS = "dependents",
  COMPANIES = "companies",
  TICKETS = "tickets",
  TICKET_TIMELINE = "ticket_timeline",
  TICKET_BENEFIT_CARD = "ticket_benefit_card",
  KPI = "kpi",
  DASHBOARDS = "dashboards",
  DASHBOARD = "dashboard",
  DASHBOARD_EMBED_URL = "dashboard_embed_url",
  PRINCIPAL_DASHBOARDS = "principalDashboards",
  INVOICES = "invoices",
  PROVIDERS = "providers",
  POLICIES = "policies",
  POLICY = "policy",
  NOTIFICATIONS = "notifications",
  BENEFICIARY_MOVEMENT_FILE_ERRORS = "beneficiaryMovementFileErrors",
  KAM_COMPANIES = "kamCompanies",
  ANALYTICS_DASHBOARDS = "analyticsDashboards",
  ANALYTICS_DASHBOARD = "analyticsDashboard",
  ANALYTICS_QUERY_EXECUTION = "analyticsQueryExecution",
}
