import {
  BenefitCardProductType,
  BenefitMovimentationStatus,
  BenefitActionType,
  TicketOperationType,
} from "../benefitService";
import { BeneficiaryAPIGender, BeneficiarySubscriberType, BeneficiaryAPI } from "./beneficiaryService.type";

const acme = { id: "acme-001", name: "Acme", document: "12.345.678/0001-90" };

const healthCard = (id: string, cardNumber: string) => ({
  id,
  cardNumber,
  productType: BenefitCardProductType.HEALTH,
  isActive: true,
  isBeingCreated: false,
  benefit: {
    id: `benefit-h-${id}`,
    accommodationType: "Apartamento",
    planLevel: "Especial",
    policy: { id: `policy-${id}`, contractCode: "CTR-2024-001", companyDocument: "12.345.678/0001-90", companyName: "Acme" },
    productType: BenefitCardProductType.HEALTH,
    provider: "Amil",
    isActive: true,
  },
  tickets: [
    {
      id: `ticket-h-${id}`,
      bid: id,
      benefit: [],
      cardNumber,
      healthCardNumber: cardNumber,
      provider: "Amil",
      productType: BenefitCardProductType.HEALTH,
      operationType: TicketOperationType.INCLUSION,
      subscriberType: "titular",
      healthBenefitName: "Plano Amil 400",
      createdAt: "2025-01-10T09:00:00Z",
      updatedAt: "2025-01-12T14:00:00Z",
      status: BenefitMovimentationStatus.COMPLETED,
      benefitActionType: BenefitActionType.INCLUSION,
    },
  ],
});

const dentalCard = (id: string, cardNumber: string) => ({
  id,
  cardNumber,
  productType: BenefitCardProductType.DENTAL,
  isActive: true,
  isBeingCreated: false,
  benefit: {
    id: `benefit-d-${id}`,
    accommodationType: undefined,
    planLevel: undefined,
    policy: { id: `policy-d-${id}`, contractCode: "CTR-2024-002", companyDocument: "12.345.678/0001-90", companyName: "Acme" },
    productType: BenefitCardProductType.DENTAL,
    provider: "Odontoprev",
    isActive: true,
  },
  tickets: [],
});

export const beneficiaryMock: BeneficiaryAPI[] = [
  // --- TITULARES ---
  {
    bid: "ben-001",
    name: "Carlos Eduardo Souza",
    document: "123.456.789-00",
    enrollmentNumber: "ACM-00001",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.HOLDER,
    gender: BeneficiaryAPIGender.MALE,
    birthDate: "1985-03-15",
    maritalStatus: "Casado(a)",
    phone: "(11) 99001-2233",
    admissionDate: "2023-02-01",
    company: acme,
    benefitCards: [
      healthCard("bc-001-h", "4001 2345 6789"),
      dentalCard("bc-001-d", "ODP-001-2345"),
    ],
  },
  {
    bid: "ben-002",
    name: "Fernanda Lima",
    document: "234.567.890-11",
    enrollmentNumber: "ACM-00002",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.HOLDER,
    gender: BeneficiaryAPIGender.FEMALE,
    birthDate: "1990-07-22",
    maritalStatus: "Casado(a)",
    phone: "(11) 98002-3344",
    admissionDate: "2023-03-15",
    company: acme,
    benefitCards: [healthCard("bc-002-h", "4001 2345 6780")],
  },
  {
    bid: "ben-003",
    name: "Roberto Alves",
    document: "345.678.901-22",
    enrollmentNumber: "ACM-00003",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.HOLDER,
    gender: BeneficiaryAPIGender.MALE,
    birthDate: "1978-11-05",
    maritalStatus: "Casado(a)",
    phone: "(11) 97003-4455",
    admissionDate: "2022-08-01",
    company: acme,
    benefitCards: [
      healthCard("bc-003-h", "4001 3456 7890"),
      dentalCard("bc-003-d", "ODP-003-3456"),
    ],
  },
  {
    bid: "ben-004",
    name: "Mariana Costa",
    document: "456.789.012-33",
    enrollmentNumber: "ACM-00004",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.HOLDER,
    gender: BeneficiaryAPIGender.FEMALE,
    birthDate: "1993-05-18",
    maritalStatus: "Solteiro(a)",
    phone: "(11) 96004-5566",
    admissionDate: "2024-01-10",
    company: acme,
    benefitCards: [dentalCard("bc-004-d", "ODP-004-4567")],
  },
  {
    bid: "ben-005",
    name: "Paulo Henrique Silva",
    document: "567.890.123-44",
    enrollmentNumber: "ACM-00005",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.HOLDER,
    gender: BeneficiaryAPIGender.MALE,
    birthDate: "1982-09-30",
    maritalStatus: "Casado(a)",
    phone: "(11) 95005-6677",
    admissionDate: "2022-11-01",
    company: acme,
    benefitCards: [healthCard("bc-005-h", "4001 4567 8901")],
  },
  {
    bid: "ben-006",
    name: "Ana Beatriz Santos",
    document: "678.901.234-55",
    enrollmentNumber: "ACM-00006",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.HOLDER,
    gender: BeneficiaryAPIGender.FEMALE,
    birthDate: "1988-01-14",
    maritalStatus: "Casado(a)",
    phone: "(11) 94006-7788",
    admissionDate: "2023-06-01",
    company: acme,
    benefitCards: [
      healthCard("bc-006-h", "4001 5678 9012"),
      dentalCard("bc-006-d", "ODP-006-5678"),
    ],
  },
  {
    bid: "ben-007",
    name: "Thiago Oliveira",
    document: "789.012.345-66",
    enrollmentNumber: "ACM-00007",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.HOLDER,
    gender: BeneficiaryAPIGender.MALE,
    birthDate: "1995-04-27",
    maritalStatus: "Solteiro(a)",
    phone: "(11) 93007-8899",
    admissionDate: "2024-03-01",
    company: acme,
    benefitCards: [healthCard("bc-007-h", "4001 6789 0123")],
  },
  {
    bid: "ben-008",
    name: "Juliana Martins",
    document: "890.123.456-77",
    enrollmentNumber: "ACM-00008",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.HOLDER,
    gender: BeneficiaryAPIGender.FEMALE,
    birthDate: "1987-12-03",
    maritalStatus: "Casado(a)",
    phone: "(11) 92008-9900",
    admissionDate: "2023-09-15",
    company: acme,
    benefitCards: [
      healthCard("bc-008-h", "4001 7890 1234"),
      dentalCard("bc-008-d", "ODP-008-6789"),
    ],
  },
  {
    bid: "ben-009",
    name: "Gustavo Ferreira",
    document: "901.234.567-88",
    enrollmentNumber: "ACM-00009",
    isBeneficiaryActive: false,
    subscriberType: BeneficiarySubscriberType.HOLDER,
    gender: BeneficiaryAPIGender.MALE,
    birthDate: "1980-06-20",
    maritalStatus: "Divorciado(a)",
    phone: "(11) 91009-0011",
    admissionDate: "2021-04-01",
    company: acme,
    benefitCards: [],
  },
  {
    bid: "ben-010",
    name: "Larissa Pereira",
    document: "012.345.678-99",
    enrollmentNumber: "ACM-00010",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.HOLDER,
    gender: BeneficiaryAPIGender.FEMALE,
    birthDate: "1992-08-11",
    maritalStatus: "Solteiro(a)",
    phone: "(11) 90010-1122",
    admissionDate: "2024-07-01",
    company: acme,
    benefitCards: [healthCard("bc-010-h", "4001 8901 2345")],
  },
  // --- DEPENDENTES ---
  {
    bid: "ben-011",
    name: "Sofia Souza",
    document: "111.222.333-01",
    enrollmentNumber: "ACM-00011",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.DEPENDENT,
    gender: BeneficiaryAPIGender.FEMALE,
    birthDate: "1987-02-10",
    maritalStatus: "Casado(a)",
    phone: "",
    company: acme,
    holder: { bid: "ben-001", name: "Carlos Eduardo Souza" },
    dependencyRelation: "Cônjuge",
    benefitCards: [healthCard("bc-011-h", "4001 2345 6790")],
  },
  {
    bid: "ben-012",
    name: "Lucas Souza",
    document: "222.333.444-02",
    enrollmentNumber: "ACM-00012",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.DEPENDENT,
    gender: BeneficiaryAPIGender.MALE,
    birthDate: "2015-06-18",
    maritalStatus: "Solteiro(a)",
    phone: "",
    company: acme,
    holder: { bid: "ben-001", name: "Carlos Eduardo Souza" },
    dependencyRelation: "Filho(a)",
    benefitCards: [healthCard("bc-012-h", "4001 2345 6791")],
  },
  {
    bid: "ben-013",
    name: "Pedro Lima",
    document: "333.444.555-03",
    enrollmentNumber: "ACM-00013",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.DEPENDENT,
    gender: BeneficiaryAPIGender.MALE,
    birthDate: "1988-09-25",
    maritalStatus: "Casado(a)",
    phone: "",
    company: acme,
    holder: { bid: "ben-002", name: "Fernanda Lima" },
    dependencyRelation: "Cônjuge",
    benefitCards: [healthCard("bc-013-h", "4001 2345 6792")],
  },
  {
    bid: "ben-014",
    name: "Isabela Costa",
    document: "444.555.666-04",
    enrollmentNumber: "ACM-00014",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.DEPENDENT,
    gender: BeneficiaryAPIGender.FEMALE,
    birthDate: "2018-03-07",
    maritalStatus: "Solteiro(a)",
    phone: "",
    company: acme,
    holder: { bid: "ben-004", name: "Mariana Costa" },
    dependencyRelation: "Filho(a)",
    benefitCards: [dentalCard("bc-014-d", "ODP-014-7890")],
  },
  {
    bid: "ben-015",
    name: "Camila Silva",
    document: "555.666.777-05",
    enrollmentNumber: "ACM-00015",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.DEPENDENT,
    gender: BeneficiaryAPIGender.FEMALE,
    birthDate: "1984-11-30",
    maritalStatus: "Casado(a)",
    phone: "",
    company: acme,
    holder: { bid: "ben-005", name: "Paulo Henrique Silva" },
    dependencyRelation: "Cônjuge",
    benefitCards: [healthCard("bc-015-h", "4001 2345 6793")],
  },
  {
    bid: "ben-016",
    name: "Mateus Santos",
    document: "666.777.888-06",
    enrollmentNumber: "ACM-00016",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.DEPENDENT,
    gender: BeneficiaryAPIGender.MALE,
    birthDate: "2012-07-14",
    maritalStatus: "Solteiro(a)",
    phone: "",
    company: acme,
    holder: { bid: "ben-006", name: "Ana Beatriz Santos" },
    dependencyRelation: "Filho(a)",
    benefitCards: [healthCard("bc-016-h", "4001 2345 6794")],
  },
  {
    bid: "ben-017",
    name: "Gabriel Oliveira",
    document: "777.888.999-07",
    enrollmentNumber: "ACM-00017",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.DEPENDENT,
    gender: BeneficiaryAPIGender.MALE,
    birthDate: "2019-01-22",
    maritalStatus: "Solteiro(a)",
    phone: "",
    company: acme,
    holder: { bid: "ben-007", name: "Thiago Oliveira" },
    dependencyRelation: "Filho(a)",
    benefitCards: [healthCard("bc-017-h", "4001 2345 6795")],
  },
  {
    bid: "ben-018",
    name: "Beatriz Martins",
    document: "888.999.000-08",
    enrollmentNumber: "ACM-00018",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.DEPENDENT,
    gender: BeneficiaryAPIGender.FEMALE,
    birthDate: "1989-04-16",
    maritalStatus: "Casado(a)",
    phone: "",
    company: acme,
    holder: { bid: "ben-008", name: "Juliana Martins" },
    dependencyRelation: "Cônjuge",
    benefitCards: [
      healthCard("bc-018-h", "4001 2345 6796"),
      dentalCard("bc-018-d", "ODP-018-8901"),
    ],
  },
  {
    bid: "ben-019",
    name: "Rafael Pereira",
    document: "999.000.111-09",
    enrollmentNumber: "ACM-00019",
    isBeneficiaryActive: true,
    subscriberType: BeneficiarySubscriberType.DEPENDENT,
    gender: BeneficiaryAPIGender.MALE,
    birthDate: "1991-10-08",
    maritalStatus: "Casado(a)",
    phone: "",
    company: acme,
    holder: { bid: "ben-010", name: "Larissa Pereira" },
    dependencyRelation: "Cônjuge",
    benefitCards: [healthCard("bc-019-h", "4001 2345 6797")],
  },
  {
    bid: "ben-020",
    name: "Eduardo Ferreira",
    document: "000.111.222-10",
    enrollmentNumber: "ACM-00020",
    isBeneficiaryActive: false,
    subscriberType: BeneficiarySubscriberType.DEPENDENT,
    gender: BeneficiaryAPIGender.MALE,
    birthDate: "2010-05-03",
    maritalStatus: "Solteiro(a)",
    phone: "",
    company: acme,
    holder: { bid: "ben-009", name: "Gustavo Ferreira" },
    dependencyRelation: "Filho(a)",
    benefitCards: [],
  },
];
